services:
  postgres:
    image: postgres:16
    container_name: esports-postgres
    environment:
      POSTGRES_DB: esports-db
      POSTGRES_USER: admin69
      POSTGRES_PASSWORD: admin69
    ports:
      - "5434:5432"
    volumes:
      - ./db/init_table.sql:/docker-entrypoint-initdb.d/01_init_table.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin69 -d esports-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: esports-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=esports-db;Username=admin69;Password=admin69
      Jwt__Key: SUPER_SECRET_KEY_123456789_SUPER_SECRET_KEY_696969696969696969
      Jwt__Issuer: Up11
      Jwt__Audience: Up11Users
      Jwt__ExpireMinutes: 60
    ports:
      - "5000:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esports-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  pgdata:
